### ISSUE TITLE
How do you make a ratchet in SimPhy? 

### ISSUE THREAD

**Issue by Megatronicus** [adamallo/SimPhy#11]
How do you make a ratchet in SimPhy?

**Comment by adamallo** [comment]
Can you be more specific? I do not know what you mean by a ratchet in this context. Thx

**Comment by Megatronicus** [comment]
Sorry for not responding immediately, I just saw you responded the same day. 

Ratchet and a pawl, like this 

![image](https://github.com/adamallo/SimPhy/assets/121646438/236997c1-2c39-4703-be27-f14882409d35)
![image](https://github.com/adamallo/SimPhy/assets/121646438/852cd930-1e0c-4f5c-800a-1f348a7c2441)
![image](https://github.com/adamallo/SimPhy/assets/121646438/2398efed-f293-4a21-ad6f-4c67ff0786a0)
![image](https://github.com/adamallo/SimPhy/assets/121646438/17095045-4234-4c9c-9983-6548ca88b365)

**Comment by leomrtns** [comment]
I'm going to go out on a limb and assume that you are thinking about a different "simphy" software. This github repo is for the simulator of gene family evolution (genomics), created in 2014, while you perhaps want the CAD-like software https://www.linkedin.com/company/simphy created in 2018

**Comment by Megatronicus** [comment]
Wow, genomics?! That's really cool. Yeah I was talking about https://www.linkedin.com/company/simphy 
It has the same name, I didn't even look at the repository or the description, just went straight here, lol. 

I was thinking of getting into genomics after programming and mechanics, I want to make people immortal so one dies ever again. Can I help you out with that? I really love solving problems, are you working on that as well, what are the main obstacles, is there a way to help?

**Comment by Megatronicus** [comment]
Check this out 
https://www.independent.co.uk/news/science/pig-blood-compound-ageing-reverse-b2442176.html

**Comment by Megatronicus** [comment]
I got ghosted lol

**Comment by adamallo** [comment]
We are not working on human immortality, but wish you good luck in your learning journey! I am closing this since it isn't an issue with SimPhy.

**Comment by Megatronicus** [comment]
> We are not working on human immortality, but wish you good luck in your learning journey! I am closing this since it isn't an issue with SimPhy.

Ah that sucks, but thanks on good wishes =) Best of luck to you too with your work.
