### ISSUE TITLE
INDELIble_wrapper.pl Error at line 411

### ISSUE THREAD

**Issue by ericopolo** [adamallo/SimPhy#3]
Hi! I'm trying SimPhy for the first time and following the tutorials in this GitHub page (Section 5.4 of the manual). When I get to case 2 we should use the INDELIble_wrapper.pl for generating alignments after the simulations, and I'm getting the following error:

`Can't exec "indelible": No such file or directory at /home/erico/bin/INDELIble_wrapper.pl line 411.`

Checking line 411 I noticed that the problem is it's calling the command "indelible" with the system function, and since I don't have any program with that name installed, the bash is returning that error to the perl interpreter. Maybe I should have something installed that I don't? I couldn't find any reference to dependencies aside from Math::GSL in the manual.

Thank you!!

**Comment by leomrtns** [comment]
Yes, you need to install idelible from here: http://abacus.gene.ucl.ac.uk/software/indelible/

(see more details here https://github.com/adamallo/SimPhy/wiki/Manual#54-sequence-simulation-using-indelible_wrapperpl)

**Comment by ericopolo** [comment]
OMG, so sorry for that! I thought the perl script was the indelible itself! My bad... Not an issue at all, except for my own lack of attention.. Thank you, leomrtns! It's working just fine now.
